version: "2"
linters:
  default: all
  disable:
    - wsl
    - varnamelen
    - testpackage
    - paralleltest
    - mnd
    - ireturn
    - gochecknoglobals
    - depguard
    - funlen
    - lll

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
