name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: lint
        uses: golangci/golangci-lint-action@master
      - uses: actions/setup-go@main
        with:
          go-version: 'stable'
      - name: Test
        run: go test -race -v ./...
