name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 */10 * *" # Runs at midnight UTC every 10th day of the month

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: lint
        uses: golangci/golangci-lint-action@v7.0.0
      - uses: actions/setup-go@main
        with:
          go-version: "stable"
      - name: Test
        run: go test -race -v ./...
